apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.mailerlite.com
spec:
  group: mailerlite.com
  names:
    kind: Email
    plural: emails
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                senderConfigRef:
                  type: string
                  description: Reference to EmailSenderConfig
                recipientEmail:
                  type: string
                  description: Receipment Email
                subject:
                  type: string
                  description: Subject of the Email
                body:
                  type: string
                  description: Body of the Email
              required:
                - senderConfigRef
                - recipientEmail
                - subject
                - body
            status:
              type: object
              properties:
                deliveryStatus:
                  type: string
                messageId:
                  type: string
